
##https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
server:
  port: 8899
#  servlet:
#    context-path: /masterhr-user
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761}
    registerWithEureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 300
spring:
  #profile: uat
  application:
    name: masterhr-user-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prasad
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl: none
        format_sql: true
        show_sql: true

